name: Update ESP web tools

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '10 10 * * * '  
jobs:
  web-tools:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: './'
      - run: |      
          # Update ESP web tools

          if [ ! -d ./webflasher/ ] ; then
            mkdir ./webflasher/
          fi

          cd ./webflasher/
          if [ ! -d temp/ ] ; then
            mkdir temp/
          fi

          cd temp/
          ver=$(curl -sL https://api.github.com/repos/esphome/esp-web-tools/releases | jq -r .[].tag_name | grep '^[0-9]\.[0-9]*\.[0-9]*$' | sort -nr | head -n1) 
          wget -q https://github.com/esphome/esp-web-tools/archive/refs/tags/${ver}.zip 
          unzip -q *.zip
          rm *.zip
          # cd esp-web-tools-${ver}/

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          cd webflasher/temp/esp-web-tools-*/ &&
          npm ci 
          wait
          script/build
          cd ..
          cd ..

          if [ ! -d web_tools/ ] ; then
          mkdir web_tools/
          fi  

          mv temp/esp-web-tools-*/dist/web/*.* web_tools/
          # echo "Web tools"
          # ls ./web_tools/
          rm -r temp/
 
          echo ''
          echo '.....'
          echo ''
          ls -l

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Update web tools'
          default_author: github_actions
          add: 'webflasher/web_tools/ --all --force'
          cwd: './'  
