name: Update ESP web tools

on:
  workflow_dispatch:
  # push:
    
jobs:
  SqueezeLite-Esp32:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: './webtools/'
      - run: |      
          # ESP web tools
          cd ./webtools/
          if [ ! -d installer/ ] ; then
            mkdir installer/
          fi
          cd installer/
          rm -r *
          ver=$(curl -sL https://api.github.com/repos/esphome/esp-web-tools/releases | jq -r .[].tag_name | grep '^[0-9]\.[0-9]*\.[0-9]*$' | sort -nr | head -n1) 
          wget -q https://github.com/esphome/esp-web-tools/archive/refs/tags/${ver}.zip 
          unzip -q *.zip
          rm *.zip
          # cd esp-web-tools-${ver}/

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          cd webtools/installer/esp-web-tools-*/
          ls -l
          npm ci
          ls -l
          script/build
          cd ..
          cd ..
          mv installer/esp-web-tools-*/dist/web installer/
          rm -r installer/esp-web-tools-*/
          echo ''
          echo '.....'
          echo ''
          ls -l


      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Update web tools installer'
          default_author: github_actions
          add: 'installer/ --all --force'
          cwd: './webtools/'  
